# Generated by Django 3.2 on 2022-12-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, verbose_name='文章名称')),
                ('excerpt', models.TextField(blank=True, max_length=255, verbose_name='文章摘要')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='排序字段')),
                ('recommend_state', models.SmallIntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, verbose_name='文章推荐状态')),
                ('header', models.TextField(verbose_name='设置锚点信息')),
                ('content', models.TextField(verbose_name='博客正文')),
            ],
            options={
                'verbose_name': '文章表',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='BloggerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_web_email', models.CharField(max_length=32, verbose_name='建站者联系邮箱')),
                ('created_web_qq', models.CharField(max_length=32, verbose_name='建站者qq')),
                ('created_web_wechat', models.ImageField(default='project_image/wechat/default.jpg', upload_to='project_image/wechat', verbose_name='建站者微信二维码')),
                ('is_show', models.CharField(choices=[('Y', '隐藏'), ('N', '不隐藏')], default='Y', help_text='Y隐藏,N不隐藏', max_length=16, verbose_name='是否隐藏')),
            ],
            options={
                'verbose_name': '网站信息表',
                'db_table': 'blogger_content',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='当前的分类表,文章要归属与当前的分类', max_length=32, unique=True, verbose_name='分类标题')),
                ('category_doc', models.TextField(max_length=255, verbose_name='分类说明')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='排序字段')),
                ('is_show', models.CharField(choices=[('Y', '隐藏'), ('N', '不隐藏')], default='Y', help_text='Y隐藏,N不隐藏', max_length=16, verbose_name='是否隐藏')),
            ],
            options={
                'verbose_name': '分类表',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=32, verbose_name='链接名称')),
                ('link', models.CharField(max_length=64, verbose_name='链接地址')),
                ('is_show', models.CharField(choices=[('Y', '隐藏'), ('N', '不隐藏')], default='Y', help_text='Y隐藏,N不隐藏', max_length=16, verbose_name='是否隐藏')),
            ],
            options={
                'verbose_name': '友情链接',
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='匿名用户', max_length=32, verbose_name='用户名')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户登录账户')),
                ('pwd', models.CharField(max_length=32, verbose_name='密文密码')),
                ('user_img', models.ImageField(default='project_image/picture/default.png', null=True, upload_to='project_image/picture', verbose_name='个人头像')),
                ('role', models.SmallIntegerField(choices=[(0, '管理员'), (1, '普通会员'), (2, '游客')], verbose_name='角色说明')),
                ('is_show', models.CharField(choices=[('Y', '停用'), ('N', '启用')], default='Y', help_text='Y停用,N启用', max_length=16, verbose_name='是否隐藏')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='ArticleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(help_text='用来记录当前留言的的昵称', max_length=32, verbose_name='留言人的名称')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('message_content', models.TextField(max_length=255, verbose_name='留言的主内容')),
                ('article', models.ForeignKey(help_text='这条留言归属与那篇文章', on_delete=django.db.models.deletion.CASCADE, related_name='message_article', to='blog.article', verbose_name='留言的归属')),
            ],
            options={
                'verbose_name': '留言表',
                'db_table': 'article_message',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_article', to='blog.category', verbose_name='当前文章归属'),
        ),
    ]
